Convert spaces to tabs

diff --git a/plugins/keepassxc/_keepassxc_cli_with_options b/plugins/keepassxc/_keepassxc_cli_with_options
--- a/plugins/keepassxc/_keepassxc_cli_with_options
+++ b/plugins/keepassxc/_keepassxc_cli_with_options
@@ -8,16 +8,16 @@ options="$1" command="$2"; shift 2
 declare -a cmd_options=()
 declare -i quiet=1
 while IFS=$'\t' read -r key value; do
-  case "${key}" in
-    yubikey) cmd_options+=("--yubikey" "${value}"); quiet=0 ;;
-    keyfile) cmd_options+=("--key-file" "${value}") ;;
-  esac
+	case "${key}" in
+		yubikey) cmd_options+=("--yubikey" "${value}"); quiet=0 ;;
+		keyfile) cmd_options+=("--key-file" "${value}") ;;
+	esac
 done < <("${parse_options}" "${options}")
 
 [[ "${command}" == "open" ]] && quiet=0
 (( quiet )) && cmd_options+=("--quiet")
 
 if ! keepassxc-cli "${command}" "${cmd_options[@]}" "$@"; then
-  echo "keepassxc-cli: Error while running the command '${command}'" >&2
-  exit 1
+	echo "keepassxc-cli: Error while running the command '${command}'" >&2
+	exit 1
 fi
diff --git a/plugins/keepassxc/ls b/plugins/keepassxc/ls
--- a/plugins/keepassxc/ls
+++ b/plugins/keepassxc/ls
@@ -6,13 +6,13 @@ options="$1" keychain_password="$2" keychain="$3" format="${4:-default}"
 
 if ! list="$("${_keepassxc_cli_with_options}" "${options}" ls --flatten --recursive "${keychain}" <<< "${keychain_password}" | { grep -v -e '/$' -e 'Recycle Bin/' || true; } | sort -f)"
 then
-  echo "Error while reading the database ${keychain}: Invalid credentials were provided, please try again." >&2
-  exit 1
+	echo "Error while reading the database ${keychain}: Invalid credentials were provided, please try again." >&2
+	exit 1
 fi
 
 if [[ "${list}" != "[empty]" ]]; then
-  case "${format}" in
-    fzf) awk '{print $0 "\t\t\t" $0}' <<< "${list}" ;;
-    *) echo "${list}" ;;
-  esac
+	case "${format}" in
+		fzf) awk '{print $0 "\t\t\t" $0}' <<< "${list}" ;;
+		*) echo "${list}" ;;
+	esac
 fi
diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -3,56 +3,56 @@ set -e
 [[ ! -f test/bats/bin/bats ]] && git submodule update --init --recursive
 
 _container_cmd() {
-  if command -v docker &>/dev/null; then
-    docker "$@"
-  elif command -v podman &>/dev/null; then
-    podman "$@"
-  elif command -v container &>/dev/null; then
-    container system start
-    container "$@"
-  else
-    echo "Error: No container runtime found. Please install either Docker or Podman and ensure it's available in your PATH." >&2
-    exit 1
-  fi
+	if command -v docker &>/dev/null; then
+		docker "$@"
+	elif command -v podman &>/dev/null; then
+		podman "$@"
+	elif command -v container &>/dev/null; then
+		container system start
+		container "$@"
+	else
+		echo "Error: No container runtime found. Please install either Docker or Podman and ensure it's available in your PATH." >&2
+		exit 1
+	fi
 }
 
 run_tests() {
-  DOCKER_BUILDKIT=1 _container_cmd build --target test -t "sschmid/pw/test/$1" -f "docker/$1/Dockerfile" .
+	DOCKER_BUILDKIT=1 _container_cmd build --target test -t "sschmid/pw/test/$1" -f "docker/$1/Dockerfile" .
 }
 
 cmd_options=()
 no_shellcheck=0
 while getopts ":ac:j:mp:" options; do
-  case "${options}" in
-    a)
-      run_tests alpine
-      run_tests archlinux
-      run_tests debian
-      run_tests fedora
-      run_tests opensuse-tumbleweed
-      run_tests ubuntu
-      ;;
-    c)
-      case "${OPTARG}" in
-        no-shellcheck) no_shellcheck=1 ;;
-      esac
-      ;;
-    j)
-      cmd_options+=("--jobs" "${OPTARG}")
-      ;;
-    m)
-      export PW_TEST_RUN_MANUAL_TESTS=1
-      cmd_options+=("--tap")
-      ;;
-    p)
-      run_tests "${OPTARG}"
-      exit
-      ;;
-    *)
-      echo "Invalid option: -${OPTARG}" >&2
-      exit 1
-      ;;
-  esac
+	case "${options}" in
+		a)
+			run_tests alpine
+			run_tests archlinux
+			run_tests debian
+			run_tests fedora
+			run_tests opensuse-tumbleweed
+			run_tests ubuntu
+			;;
+		c)
+			case "${OPTARG}" in
+				no-shellcheck) no_shellcheck=1 ;;
+			esac
+			;;
+		j)
+			cmd_options+=("--jobs" "${OPTARG}")
+			;;
+		m)
+			export PW_TEST_RUN_MANUAL_TESTS=1
+			cmd_options+=("--tap")
+			;;
+		p)
+			run_tests "${OPTARG}"
+			exit
+			;;
+		*)
+			echo "Invalid option: -${OPTARG}" >&2
+			exit 1
+			;;
+	esac
 done
 shift $(( OPTIND - 1 ))
 
