keepassxc: Print error message to highlight errors which may be overseen

diff --git a/src/plugins/keepassxc/_keepassxc_cli_with_options b/src/plugins/keepassxc/_keepassxc_cli_with_options
--- a/src/plugins/keepassxc/_keepassxc_cli_with_options
+++ b/src/plugins/keepassxc/_keepassxc_cli_with_options
@@ -17,4 +17,7 @@ done < <("${parse_options}" "${options}")
 [[ "${command}" == "open" ]] && quiet=0
 (( quiet )) && cmd_options+=("--quiet")
 
-keepassxc-cli "${command}" "${cmd_options[@]}" "$@"
+if ! keepassxc-cli "${command}" "${cmd_options[@]}" "$@"; then
+  echo "keepassxc-cli: Error while running the command '${command}'" >&2
+  exit 1
+fi
