Rename Docker* to Container*

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -3,21 +3,21 @@ set -e
 [[ ! -f test/bats/bin/bats ]] && git submodule update --init --recursive
 
 _container_cmd() {
-	if command -v docker &>/dev/null; then
-		docker "$@"
-	elif command -v podman &>/dev/null; then
+	if command -v podman &>/dev/null; then
 		podman "$@"
+	elif command -v docker &>/dev/null; then
+		docker "$@"
 	elif command -v container &>/dev/null; then
 		container system start
 		container "$@"
 	else
-		echo "Error: No container runtime found. Please install either Docker or Podman and ensure it's available in your PATH." >&2
+		echo "Error: No container runtime found. Please install Podman, Docker or Apple container and ensure it's available in your PATH." >&2
 		exit 1
 	fi
 }
 
 run_tests() {
-	DOCKER_BUILDKIT=1 _container_cmd build --target test -t "sschmid/pw/test/$1" -f "docker/$1/Dockerfile" .
+	DOCKER_BUILDKIT=1 _container_cmd build --target test -t "sschmid/pw/test/$1" -f "container/$1/Containerfile" .
 }
 
 cmd_options=()
